### ISSUE TITLE
[PROPOSAL] A textual representation of device configurations

### ISSUE THREAD

**Issue by hyunsik** [furiosa-ai/device-api#17]
전에 말씀드린 텍스트 형태로 device config를 비롯한 다양한 device 설정을 text로 하기 위한 제안입니다. 우선 순수한 제안이고요. 우선순위가 급하지는 않지만 대략적으로 Q2 내에는 이런 기능이 추가되어야 하지 않을까 생각합니다.

유스케이스가 다음과 같습니다.
* 서빙 프레임워크의 설정 파일
* 작성된 응용에서 사용할 디바이스를 코드 변경 없이 외부에서 설정할 때

우선 제안 드리는 텍스트 표현은 다음과 같습니다. `FURIOSA_DEVICES` 는 `NPU_DEVNAME`을 대체하는 새로운 환경변수 이름입니다.
```
# Using specific device names
FURIOSA_DEVICES="0:0" # npu0pe0
FURIOSA_DEVICES="0:0-1" # npu0pe0-1

# Using device configs
FURIOSA_DEVICES="warboy*2" # warboy multi core mode x 2
FURIOSA_DEVICES="warboy(1)*2" # single pe x 2
FURIOSA_DEVICES="warboy(2)*2" # 2-pe fusioned x 2

# Using device configs with a random device 
# It can be commonly used because most of systems will have a single kind of NPUs.
FURIOSA_DEVICES="npu(2)*2" # any 2-pe fusioned device x 2

# When we use multiple models in a single application
FURIOSA_DEVICES="APP1=warboy*2, APP2=warboy(2)*2" # Allow to specify two different device configurations for two applications 'APP1' and 'APP2'
```

**Comment by sukyoungjeong-furiosa** [comment]
당장의 usage는 없겠지만 `npu(1) + npu(2)*2` 같이 덧셈 기호도 잘 정의되네요. notation의 직관성이 좋은거 같습니다!

한가지는, warboy 라고 쓰면 적당한 default 값이 아니라 multi core mode가 선택되는게 저는 조금 걸리는데요, 크게 무리는 없을것 같습니다.
