### ISSUE TITLE
Publishing v0.1.0 on crates.io

### ISSUE THREAD

**Issue by sukyoungjeong-furiosa** [furiosa-ai/device-api#2]
The following tasks are to be done before publishing on crates.io:

- [x] Add README
- [x] Add LICENSE
- [x] Add license, description, etc., to Cargo.toml
- [x] Documentation for the api
- ~~Add contribution guide, w/ coding convention~~ (as future work if needed)

cf. https://doc.rust-lang.org/cargo/reference/publishing.html

**Comment by sukyoungjeong-furiosa** [comment]
Performing some checks before publishing as the reference suggests. #26

**Comment by sukyoungjeong-furiosa** [comment]
Published as v0.1.0-alpha on crates.io (https://crates.io/crates/furiosa-device).

**Comment by sukyoungjeong-furiosa** [comment]
Close this issue as v0.1.0 is published

**Comment by hyunsik** [comment]
Thank you for this work! It's one big step for this project.
