### ISSUE TITLE
Retrieving NUMA node ID

### ISSUE THREAD

**Issue by sukyoungjeong-furiosa** [furiosa-ai/device-api#28]
It would be useful if we can retrieve NUMA node ID associated with the NPU device's PCI lane.

cf)
![image](https://user-images.githubusercontent.com/99079696/170645037-596069c9-22eb-4f58-874a-94486455f056.png)

Currently, one can retrieve NUMA node ID as follows:

```
root@sukyoungjeong-npu-0:~# cat /sys/class/npu_mgmt/npu5_mgmt/busname
0000:ce:00.0
root@sukyoungjeong-npu-0:~# cat /sys/bus/pci/devices/0000\:ce\:00.0/numa_node
1
```

**Comment by libc-furiosa** [comment]
관련하여 도움이 될만한 문서 몇 가지를 남깁니다. 다른 좋은 레퍼런스를 아는게 있으시다면 추가로 공유해주시면 좋을 것 같습니다.

* https://docs.kernel.org/vm/numa.html
* https://support.mellanox.com/s/article/understanding-numa-node-for-performance-benchmarks
* https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-integration-with-the-topology-manager
