### ISSUE TITLE
DeviceConfig for named multicore device

### ISSUE THREAD

**Issue by sukyoungjeong-furiosa** [furiosa-ai/device-api#38]
Few test cases in `npu-tools` utilize `send`/`recv` commands of a Multicore device.

Successively from #35 , we need to support DeviceConfig to express named Multicore device.

**Comment by sukyoungjeong-furiosa** [comment]
cf. https://github.com/furiosa-ai/device-api/issues/17

@hyunsik , @libc-furiosa

(1) npu0와 같은 multicore mode를 지칭하는 표현을 어떤것을 사용하면 좋을까요?
현재 `"0:0"`으로 쓰면 npu0pe0, `"0:0-1"`로 쓰면 npu0pe0-1 입니다.
`<index>:<core>` 외에 npu0, npu0pe0와 같은 표현법을 동시에 허용하는 방법도 있는데요,
저는 직관적인 표현법이 떠오르지 않아서 여차하면 이 방향을 택하려 합니다.

(2) device config로 multicore를 지칭하는 표현도 아직 구현으로 반영되지 않았는데요.
이전에 (괄호 없이) `warboy*2`로 쓰면 warboy multicore mode *2 로 제안 주셨던 것을 반영하려 합니다. 다른 의견 있으시면 부탁드립니다.

**Comment by hyunsik** [comment]
(1) 저도 `0` 과 같이 device id만 쓰는 방법이 간결해서 좋을 것 같습니다. 여러 device 를 지정하는 경우 (`0,1`)도 잘 적용될 것 같고요.
(2) 괄호 없이 `warboy` or `warboy*2` 좋은 것 같습니다.
