### ISSUE TITLE
warboy*2 should be equivalent(1) to warboy(1)*2?

### ISSUE THREAD

**Issue by hyunsik** [furiosa-ai/device-api#52]
## Background
`warboy*2` 와 같이 `(N)` 이 없는 경우 multi-core 모드로 동작합니다. multi-core 는 조금 더 특별한 경우기 때문에 명시적으로 특별한 notation 이 필요하다고 생각합니다.

## Proposal
* pe 개수 `(N)` 없이 장치 이름만 지정하는 경우 1개 pe 에 대응되도록 변경합니다.
* warboy(*) 를 multi-core 를 가리키는 표현으로 사용합니다.
* `*`이 여러 의미로 쓰이는 것을 방지하고 더 직관적인 표현을 위해 기존 * 를 x 로 변경합니다.
  * 예) warboy(1)x2

변경전:
* warboy*2 => warboy multicore mode x 2
* warboy(1)*2 => warboy 1 pe x 2
* warboy(2)*2 => warboy fusioned 2 pe x 2

변경후:
* warboy x 2 => warboy 1 pe x 2
* warboy(1)x2 => warboy 1 pe x 2
* warboy(2)x2 => warboy fusioned 2 pe x 2
* warboy(*)x2 => warboy multicore mode x 2 (더 좋은 notation 이 있으면 제안 주셔도 좋습니다)

@libc-furiosa @sukyoungjeong-furiosa 논의를 시작해보고자 하는 이슈이니 편히 의견 주시면 감사하겠습니다.

**Comment by sukyoungjeong-furiosa** [comment]
제안 감사합니다 ㅎㅎ 원래 (*)를 고려했었는데, 말씀주신대로 separator가 여러 의미가 되면 nom parser combinator 쓰기가 안좋았던 기억이네요.

`warboy`처럼 parenthesis 없이 사용할때 mode를 변경하는것에는 동의합니다. 용례가 어느쪽이 많은지에 따라 2pe를 default 해도 될것같습니다. `DeviceConfig::default()` 하면 fused가 나와서 어느 한쪽으로 통일하면 좋을것같네요.

notation 관련해서는, warboy x 2 보다 warboy*2 로 쓰는게 너무 편해 보이네요.

**Comment by hyunsik** [comment]
@sukyoungjeong-furiosa 네 `*` 는 현재로 유지하고 default mode가 변경되면 좋을 것 같습니다.
